// questions
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const OVERWRITE_QUESTIONS = 'OVERWRITE_QUESTIONS';
export const HANDLE_GET_QUESTIONS = 'HANDLE_GET_QUESTIONS';
export const HANDLE_OVERWRITE_QUESTIONS = 'HANDLE_OVERWRITE_QUESTIONS';


export const GET_ANSWERS = 'GET_ANSWERS';
export const OVERWRITE_ANSWERS = 'OVERWRITE_ANSWERS';
export const RESET_ANSWERS = 'RESET_ANSWERS';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';
export const RESET_ANSWERSLIST = 'RESET_ANSWERSLIST';
export const HANDLE_GET_ANSWERS = 'HANDLE_GET_ANSWERS';
export const HANDLE_OVERWRITE_ANSWERS = 'HANDLE_OVERWRITE_ANSWERS';

export const GET_LIKES = 'GET_LIKES';
export const HANDLE_LIKES = 'HANDLE_LIKES';
export const RESET_LIKES = 'RESET_LIKES';

export const SET_CURR_QUESTIONID = 'SET_CURR_QUESTIONID';

// user
export const SET_USER = 'SET_USER';
export const GET_USERS = 'GET_USERS';

//edits
export const SET_CURRENT_EDIT_ID = 'SET_CURRENT_EDIT_ID';
export const UPDATE_EDIT_BY_TYPE_AND_ID = 'UPDATE_EDIT_BY_TYPE_AND_ID';